---
title: "Plot Prioritization"
author: "Shive Lab (B. Baker)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)
library(terra)
library(janitor)

```

```{r data}

groves <- vect(here("data/spatial_data/SEKI_groves/SEKI_groves_list.shp")) %>% 
  st_as_sf()

existing_plots <-read_csv(here("data/spatial_data/all_plots_groves_env.csv"))

aspect <- vect(here("data/spatial_data/aspect_polys.shp")) %>% 
  st_as_sf() %>% 
  st_transform(crs(groves))

trt <- vect(here("data/spatial_data/trt/SEGI_Trtdata_05feb25.shp")) %>% 
  project(crs(groves))

fire <- vect(here("data/spatial_data/cbi_all/cbi_all.shp")) %>% 
  project(crs(groves))

no_fire <- read_sf(here("data/spatial_data/no_fire/no_fire.shp")) %>% 
  st_transform(crs(groves))

plots_sf <- st_read(here("data/spatial_data/all_plots_groves.shp")) 

access <- read.csv(here("data/grove_access.csv"))
```



```{r transform}
#ks: Bri's way worked for me the first time around, then totally unrelated stuff started freezing, so I deleted the whole enviro and started over, then this process of converting within the piped code didn't work anymore (??). So I did it outside of the piped code and seems to work for me now

# groves_vect <- vect(groves)
# aspect_vect <- vect(aspect)

fire <- fire %>% 
  st_as_sf()

trt <- trt %>% 
  st_as_sf()

rx_seki <- trt %>% 
  # st_as_sf() %>% 
  filter(treatment == "Fire-related treatment") %>%  
  # vect() %>% 
  st_intersection(groves) %>% 
  # st_as_sf() %>% 
  st_collection_extract(type = c("POLYGON"), warn = FALSE) %>% 
  mutate(burnsev = 2,
         id = paste(grov_nm, year, rowid, sep = "_"))%>% 
  rename(fire_yr = year)%>% 
  select(id, fire_yr, burnsev)

no_burn <- no_fire %>% 
  mutate(
    burnsev = 0,
    fire_yr = 0000,
    id = "unburned"
  )%>% 
  select(id, fire_yr, burnsev)
  

# aspect_groves <- intersect(aspect_vect, groves_vect) %>% 
#   st_as_sf()%>% 
aspect_groves <- aspect %>%
  st_intersection(groves) %>% 
  #ks: changed names for aspect to make briefer strata names later
  mutate(aspect = case_when(
    Id == 1 ~ "NW_E",
    Id == 2 ~ "SE_W"
  ))


# burn <- intersect(fire, groves_vect) %>% 
#   st_as_sf()%>%
burn <- fire %>%
  st_intersection(groves) %>%
  mutate(fire_yr = as.numeric(fire_yr)) %>% 
  select(id, fire_yr, burnsev) %>% 
  bind_rows(rx_seki) %>% 
  bind_rows(no_burn)


grove_area <- sum(groves$grovr_h)
```

```{r plots}

plot_types <- existing_plots %>% 
  summarize(.by = c(grove_name, project), count = n()) %>% 
  pivot_wider(names_from = project, values_from = count) %>% 
  adorn_totals()

write_csv(plot_types, here("data/plotTypes.csv"))

plots_rx <- st_intersection(rx_seki, plots_sf)

plots_rx_count <- plots_rx %>% 
  st_drop_geometry() %>% 
  summarise(.by = plot_id, trt_ct = n())

plots_rx_yr <- plots_rx %>% 
  group_by(plot_id) %>% 
  slice_max(fire_yr) %>% 
  rename(trt_yr = fire_yr) %>% 
  left_join(plots_rx_count) %>% 
  mutate(sev = "Low") %>% 
  select(plot_id, trt_yr, trt_ct, sev) %>% 
  st_drop_geometry()


totals_summary <- existing_plots %>% 
  summarise(.by = c(grove_name), total = n())

plot_total <-  sum(totals_summary$total)

plots_all <- existing_plots %>% 
  left_join(plots_rx_yr) %>% 
  replace_na(list(trt_yr = 0000, trt_ct = 0, sev = "Unburned")) %>% 
  mutate(
    fire_yr = as.numeric(fire_yr),
    burnsev = case_when(fire_yr<trt_yr ~ sev, T ~ burnsev),
    fire_yr = case_when(fire_yr<trt_yr ~ trt_yr, T ~ fire_yr),
    fire_count = fire_count+trt_ct
  )

plots_classified <- plots_all %>% 
   mutate(
     burnsev = case_when(burnsev == "Undetected change" ~ "Unburned",
                         T ~ burnsev),
    #ks: changed names for aspect and time_since to make briefer strata names later
     aspect = case_when(
     aspect <= 90 | aspect > 315~ "NW_E",
     T ~ "SE_W"),
     time_since = case_when(
       fire_yr == 0000 ~ "over5",
       fire_yr  >= 2020 ~ "under5",
       T ~ "over5"
     ),
     count = case_when(fire_count >= 2 ~ "many",
                      T ~ "one"))

plot_sets <- plots_classified %>% 
  summarize(.by = c(aspect, burnsev, time_since, count), count_plot = n()) %>% 
  #ks: changed names for count_v2 to make briefer strata names later
  mutate(count_v2 = case_when(burnsev == "Unburned" ~ "none", T ~ count)) %>%
  mutate(strata_nm = paste(aspect,"-",time_since,"-",burnsev,"-",count_v2, sep = "")) %>%
  group_by(aspect,burnsev,time_since,count_v2,strata_nm) %>%
  summarise(count_plot = sum(count_plot)) %>%
  mutate(prop_plot = round(count_plot/plot_total, 2))


```

```{r grove_setup}

burn_count <- burn %>% 
  summarize(.by = c(id, fire_yr, burnsev), geometry = st_combine(geometry)) %>% 
  st_make_valid() %>% 
  arrange(-fire_yr)

burn_id <- burn_count %>% 
  st_drop_geometry() %>% 
  rowid_to_column("rid")

fire_count <- st_intersection(burn_count) %>% 
  st_collection_extract(type = c("POLYGON"), warn = FALSE)

burn_classed <- fire_count %>%
  mutate(time_since = case_when(
       fire_yr == 0000 ~ "over5",
       fire_yr  >= 2020 ~ "under5",
       T ~ "over5"
     ),
    burnsev = case_when(
      burnsev == 0 ~ "Unburned",
      burnsev == 1 ~ "Unburned",
      burnsev == 2 ~ "Low",
      burnsev == 3 ~ "Moderate",
      burnsev == 4 ~ "High",
      T ~ "Unburned"
     ),
    #ks: changed names for count to make briefer strata names later
    count = case_when(n.overlaps >= 2 ~ "many",
                      T ~ "one")) %>%
  summarize(.by = c(time_since, burnsev, count), geometry = st_combine(geometry)) %>% 
  st_make_valid() 


groves_set <- burn_classed %>% 
  st_intersection(aspect_groves) %>% 
  st_collection_extract(type = c("POLYGON"), warn = FALSE) %>% 
  summarize(.by = c(aspect, time_since, burnsev, count), geometry = st_combine(geometry)) %>% 
  st_make_valid() %>% 
  mutate(area_ha = as.numeric(st_area(.))*0.0001,
         prop_area = round(area_ha/grove_area, 2)) #%>% 
  # st_drop_geometry()
  
  
#make polys and select for only slivers >5 acres
groves_classified_poly = st_collection_extract(groves_set, "POLYGON") %>%
  #lines were created, convert back to polygon
  st_cast("POLYGON") %>%
  mutate(area_ha = as.numeric(st_area(.))*0.0001) %>%
  #filter out individual silvers <5 acres
  filter(area_ha > 2.02343) %>%
  #regroup by strata
  mutate(count_v2 = case_when(burnsev == "Unburned" ~ "none", T ~ count)) %>%
  group_by(aspect, time_since, burnsev, count_v2) %>%
  summarise(area_ha = sum(area_ha)) %>%
  #create unique strada ID
  mutate(strata_nm = paste(aspect,"-",time_since,"-",burnsev,"-",count_v2, sep = ""), 
         prop_area = round(area_ha/grove_area, 2))
nrow(groves_classified_poly)  


# write_sf(groves_classified_poly, here("data/spatial_data/outputs/groveset_wGroveNames_over5acres.shp"))
#write_sf(groves_set, here("data/spatial_data/debug_groveset.shp"))


#aspect_poly <- st_read(here("data/spatial_data/aspect_polys.shp")) %>% 
 # transform(st_crs(burn_classed))


```

```{r}

# comparison_sets <- groves_set %>% 
#   left_join(plot_sets) %>% 
#   replace_na(list(prop_plot = 0, count_plot = 0)) %>% 
#   mutate(count = case_when(burnsev == "Unburned" ~ "none",
#                            count == "multiple" ~ count,
#                            T ~ "one"),
#          area_ha = round(area_ha, 2),
#          diff = prop_area - prop_plot,
#          total.plots.needed = round(458*prop_area),
#          useful.plots = case_when(count_plot>total.plots.needed ~ total.plots.needed,
#                                   T ~ count_plot),
#          NEW.plots.needed = total.plots.needed - useful.plots)
# 
# write_csv(comparison_sets, here("data/strata_set_comparison_20Feb25.csv"))

##get needed number of plots based on area of strata
needed.strata.plots <- groves_classified_poly %>% 
  left_join(plot_sets) %>% 
  # replace_na(list(prop_plot = 0, count_plot = 0)) %>% 
  mutate( count = case_when(burnsev == "Unburned" ~ "none",
                           count_v2 == "many" ~ count_v2,
                           T ~ "one"),
         area_ha = round(area_ha, 2),
         diff = prop_area - prop_plot,
         total.plots.needed = round(458*prop_area),
         useful.plots = case_when(count_plot>total.plots.needed ~ total.plots.needed,
                                  T ~ count_plot),
         NEW.plots.needed = total.plots.needed - useful.plots) %>%
  filter(NEW.plots.needed > 0)

##Create new shapefile that removes "Very Difficult" access groves, and dissolve into one big shapefile
access.min = access %>% select(grove,Ease.of.Access)

groves_easier = groves %>% 
  mutate(grove = grove_name) %>%
  left_join(access.min) %>%
  filter(Ease.of.Access != "Very Difficult") %>%
  # st_buffer(0.5) %>% # make a buffer of half a meter around all parts (to avoid slivers)
  st_union() %>% # unite to a geometry object
  st_sf() %>% # make the geometry a data frame object
  mutate(keep = T)

#intersect the remaining strata with the "easier" groves
needed.strata.plots_easier.1 = needed.strata.plots %>%
  st_intersection(groves_easier) %>%
  select(aspect:strata_nm) 

#create a table to join the details on plots needed per strata back
needed.strata.plots_table = needed.strata.plots %>%
  st_drop_geometry()

#join the table to the reduced strata shapefile
needed.strata.plots_easier = needed.strata.plots_easier.1 %>%
  left_join(needed.strata.plots_table) %>%
    st_cast("MULTIPOLYGON")
needed.strata.plots_easier$area_ha = st_area(needed.strata.plots_easier)*0.0001

needed.strata.plots_easier_table = needed.strata.plots_easier %>%
  st_drop_geometry()
write.csv(needed.strata.plots_easier_table, here("data/plot_needs_by_strata_2May2025_kls.csv"))

##split by attributes to get individual shapefiles for the GRTS
#select the column of the attribute table for the split
unique <- unique(needed.strata.plots_easier$strata_nm)

#create new polygons based on the unique column ID
for (i in 1:length(unique)) {
  tmp <- needed.strata.plots_easier[needed.strata.plots_easier$strata_nm == unique[i], ]
  write_sf(tmp, here("data/spatial_data/ind_strata"), unique[i], driver="ESRI Shapefile",
           overwrite_layer=TRUE)
}

```


#Summarize plots by grove and rank

```{r}
# grove_plot_sets <- plots_classified %>% 
#   summarize(.by = c(grove_name, aspect, burnsev, time_since, count), count_plot = n()) %>% 
#   mutate(prop_plot = round(count_plot/plot_total, 2))
# 
# bygroves_set <- burn_classed %>% 
#   st_intersection(aspect_groves) %>% 
#   st_collection_extract(type = c("POLYGON"), warn = FALSE) %>% 
#   summarize(.by = c(grov_nm, aspect, time_since, burnsev, count), geometry = st_combine(geometry)) %>% 
#   st_make_valid() %>% 
#   mutate(area_ha = as.numeric(st_area(.))*0.0001,
#          prop_area = round(area_ha/grove_area, 2)) %>% 
#   st_drop_geometry()
#   
# grovecomparison_sets <- bygroves_set %>% 
#   left_join(grove_plot_sets, join_by(grov_nm == grove_name, aspect, time_since, burnsev, count)) %>% 
#   replace_na(list(prop_plot = 0, count_plot = 0)) %>% 
#   mutate(count = case_when(burnsev == "Unburned" & count == "one or none"~ "one or none",
#                            count == "multiple" ~ count,
#                            T ~ "one"),
#          area_ha = round(area_ha, 2),
#          diff = prop_area - prop_plot) 
# 
# write_csv(grovecomparison_sets, here("data/grove_strata_set_comparison_19March25.csv"))

##this table made in "existing_plots_assessment.Rmd"
groves_seki_summary = read.csv(here("outputs/groves_seki_summary.csv"))
plots_sf$grove_name = plots_sf$grov_nm

#make grove summary plot, nonspatial
groves_summary <- plots_sf %>% 
  st_drop_geometry() %>% #remove polygon reference
  summarize(.by = c(grove_name, project), plot_count = n()) %>% #count per type
  pivot_wider(names_from = project, # make wider dataframe for viz
              values_from = plot_count, 
              values_fill = 0) %>% 
  adorn_totals("col") %>% #calc total plots per grove
  # adorn_totals() %>%  #calc total plots per type
  left_join(groves_seki_summary) %>% # add grove info
  mutate(plots_peracre_buf = round(Total/groveacres,2),
         acres_perplot_buf = round(groveacres/Total, 0),
         groveacres = round(groveacres,0),
         total.existing.plots = Total) %>%
  select(-c(2:7))
# View(groves_summary)

hist(groves_summary$total.existing.plots)
hist(groves_summary$acres_perplot_buf, breaks = 100)

##rough ranking based on total plots and plot density
groves_summary_rank = groves_summary %>%
  mutate(total.plots.rank = 
           case_when(total.existing.plots <10 ~ "very few plots",
                    total.existing.plots >=10 & 
                      total.existing.plots <30 ~ "moderate plots",
                    total.existing.plots >=30 ~ "lotsa plots",
                        .default = "oopsie"),
         plot.density.rank = 
           case_when(acres_perplot_buf <10 ~ "high density",
                    acres_perplot_buf >=10 & 
                      acres_perplot_buf <50 ~ "moderate density",
                    acres_perplot_buf >=50 ~ "low density",
                      .default = "oopsie"),
         combo.rank = paste(total.plots.rank,"-",plot.density.rank))
  
# View(groves_summary_rank)  
write.csv(here("outputs/groves_summary_rank.csv"))



```



# Plots Needed

```{r}
#grove info
grove_plots <- grove_plot_sets %>% 
  summarise(.by = grove_name, plots = sum(count_plot))

grove_access <- readxl::read_excel(here("data/grove_prioritization.xlsx"), "grove_access") %>%   clean_names() %>% 
  select(grove, grove_ha, ease_of_access) %>% 
  mutate(grove_acres = grove_ha*2.471) %>% 
  rename(grove_name = grove) %>% 
  left_join(grove_plots) %>% 
  replace_na(list(plots = 0)) %>% 
  mutate(total_per = plots/grove_acres)


```


```{r}
plots_needed <- readxl::read_excel(here("data/grove_prioritization.xlsx"), "plot_needs") %>% 
  clean_names() %>% 
  rowid_to_column()

visit_groves_setup <- grovecomparison_sets %>% 
  rename(
    set_area_ha = area_ha,
    set_prop_area = prop_area,
    set_prop_plot = prop_plot,
    set_count = count_plot,
    set_diff = diff) %>% 
  mutate(set_area_acres = set_area_ha*2.471) %>% 
  left_join(grove_access, join_by(grov_nm == grove_name)) %>% 
  mutate(grove_plots = plots) %>% 
  left_join(plots_needed, join_by(aspect, time_since, burnsev, count)) %>% 
  select(rowid, aspect, time_since, burnsev, count, grov_nm, set_area_acres, set_diff,
         ease_of_access, grove_acres, grove_plots, total_per, prop_area, count_plots_needed) 

#this filters out 3 of the very uncommon strata 
visit_groves <- visit_groves_setup%>% 
  filter(set_area_acres >= 50, 
         count_plots_needed > 0, 
         ease_of_access != "Very Difficult"
         ) %>% 
  arrange(aspect, time_since, burnsev, count)


#check how many strata
visit_groves_have <- visit_groves %>% 
  summarise(.by= c(aspect, time_since, burnsev, count))

#isolate the 3 that are missing
need_plots_missing<- plots_needed %>% 
  filter(count_plots_needed > 0) %>% 
  arrange(area_ha) %>% 
  head(3)

add_groves <- visit_groves_setup %>% 
  filter(rowid %in% unique(need_plots_missing$rowid)) %>% 
  filter(set_area_acres>=3, ease_of_access != "Very Difficult") 

#combine
visit_groves <- visit_groves %>% 
  rbind(add_groves)

write_csv(visit_groves, here("data/filtered_grove_options.csv"))

```



```{r}

summary_visit_grove <- visit_groves %>% 
  summarise(.by = grov_nm, new_strata = n(), strata_list = list(rowid)) %>% 
  left_join(grove_access, join_by(grov_nm == grove_name)) %>% 
  mutate(strata_list = paste(strata_list))
write_csv(summary_visit_grove, here("data/grove_options.csv"))

summary_visit_strata <- visit_groves %>% 
  summarise(.by = rowid, groves = n(), grove_list = list(grov_nm)) %>% 
  left_join(plots_needed) %>% 
  mutate(grove_list = paste(grove_list))
write_csv(summary_visit_strata, here("data/strata_options.csv"))



```


